apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, role:admin, role:readonly
    g, admin, role:admin

    p, role:readonly, applications, get, *, allow
    p, role:readonly, projects, get, *, allow

    p, role:admin, repositories, get, *, allow
    p, role:admin, applications, sync, default/*, allow
