apiVersion: batch/v1
kind: Job
metadata:
  name: ai-advisor-job
  namespace: argo-tips
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "4"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ai-advisor
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            echo "🤖 AI Advisor is checking deployment..."
            echo "📊 Number of replicas: $(kubectl get deploy argo-tips -n argo-tips -o jsonpath='{.status.replicas}')"
            echo "✅ Suggestion: scale replicas if needed!"
