apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-waves
  namespace: argo-tips
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "3"
spec:
  template:
    metadata: 
      labels:
        job-name: post-sync-waves
    spec:
      restartPolicy: Never
      containers:
      - name: curl
        image: curlimages/curl:8.9.1
        command: ["sh","-c"]
        args:
          - |
            echo "Running smoke test against argo-tips service..."
            curl -sSf http://argo-tips.argo-tips.svc.cluster.local:80/ \
              && echo "✅ Smoke test passed!" \
              || (echo "❌ Smoke test failed!" && exit 1)


