apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  namespace: argo-tips
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: pre-sync
        image: busybox
        command: ["sh", "-c", "echo 'Running pre-sync task!'"]
      restartPolicy: Never
