apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-tips
  namespace: argocd
spec:
  destination:
    namespace: argo-tips
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/revitalbarletz/argo-tips.git
    targetRevision: main
    path: manifests
    manifestGeneratePaths:
      - manifests/namespace
      - manifests/configmap
      - manifests/deployment
      - manifests/service
      - manifests/hooks/pre-sync-waves
      - manifests/hooks/post-sync-waves
      - manifests/hooks/ai-agent-scripts
      - manifests/hooks/ai-advisor-cronjob
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
