apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-tips
  namespace: argocd
  annotations:
    # Track the image you're actually using (Docker Hub)
    argocd-image-updater.argoproj.io/image-list: web=revitalbar/argo-tips

    # Choose new versions by SemVer, but only from tags that look like "v1.2" or "v1.2.3"
    argocd-image-updater.argoproj.io/web.update-strategy: semver
    argocd-image-updater.argoproj.io/web.allow-tags: "regexp:^v\\d+\\.\\d+(\\.\\d+)?$"

    # Write updates back to Git via the Argo CD "source hint" file
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-tips
  project: default
  source:
    repoURL: https://github.com/revitalbarletz/argo-tips.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
