apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-tips
  namespace: argocd
  annotations:
    # Tell AIU what to track (alias "web")
    argocd-image-updater.argoproj.io/image-list: web=ghcr.io/revitalbarletz/argo-tips

    # Policy
    argocd-image-updater.argoproj.io/web.update-strategy: semver
    argocd-image-updater.argoproj.io/web.allow-tags: ">=1.0.0"
    argocd-image-updater.argoproj.io/web.ignore-tags: "*rc*,*beta*,*pr-*"

    # Write-back via Git (creates .argocd-source-argo-tips.yaml by default)
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-tips
  project: default
  source:
    repoURL: https://github.com/revitalbarletz/argo-tips.git
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
