apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-tips
  namespace: argo-tips 
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # optional: set a sync wave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-tips
  template:
    metadata:
      labels:
        app: argo-tips
    spec:
      containers:
      - name: web
        image: revitalbar/argo-tips:v1.5
        ports:
        - containerPort: 80
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: argo-tips-config
              key: APP_MESSAGE
