# manifests/kustomization.yaml
resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml

# This is the knob AIU will turn:
images:
  - name: revitalbar/argo-tips
      newTag: "v1.5"   # <— set to the tag you're currently running 
